### ISSUE TITLE
No error gets generated when the ChunkSize is greater than the array size itself

### ISSUE THREAD

**Issue by jm9176** [mathworks/MATLAB-support-for-Zarr-files#30]
No error gets generated if the ChunkSize is set greater than the array size. This MATLAB behavior seems consistent with the behavior verified using Zarr library in Python.

The following code stores the data as a single chunk.

```
>> zarrcreate('test_files/arr1',[5 5],'ChunkSize',[10 10])
>> zarrwrite('test_files/arr1',ones(5,5))
>> zarrread('test_files/arr1')

ans =

     1     1     1     1     1
     1     1     1     1     1
     1     1     1     1     1
     1     1     1     1     1
     1     1     1     1     1 
```

**Comment by abhibaruah** [comment]
Fixed by https://github.com/mathworks/MATLAB-support-for-Zarr-files/commit/c1817d748ef582ded94cfa06ea74a48336f151dd

**Comment by jm9176** [comment]
@abhibaruah I am using the latest changes, but I still see this error. Could you please confirm? Re-opening this issue for now

```
>> zarrcreate('test_file/arr1',[10 10],'ChunkSize',[20 20])
>> zarrinfo('test_file/arr1')

ans = 

  struct with fields:

                 chunks: [2×1 double]
             compressor: []
    dimension_separator: '.'
                  dtype: '<f8'
             fill_value: []
                filters: []
                  order: 'C'
                  shape: [2×1 double]
            zarr_format: 2
              node_type: 'array'
```

**Comment by abhibaruah** [comment]
I do not see this issue anymore
```MATLAB
>> zarrcreate('test_file/arr1',[10 10],'ChunkSize',[20 20])
Error using zarrcreate (line 100)
Invalid chunk size. Each entry of ChunkSize must be less than or equal to the corresponding entry of datasize.
```
